# Site settings
title: OscarJavierHernandez
markdown: kramdown
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oscar Javier Hernandez
user_description1: Problem solving physics PhD candidate leveraging my quantitative skills to transition into data science. My research employs a range of statistical and numerical methodologies to produce state-of-the art calculations essential for precision experiments. 
user_description2: With a background in theoretical and computational nuclear physics, I have 5+ years’ experience implementing algorithms to solve complex mathematical problems. My analytical and computational specialization drive my passion for data science and machine learning - collecting and analyzing data sets; building accurate AI models and generating impactful predictions with quantified uncertainty estimates.
user_description3: I am a results oriented researcher and communicator, producing 7 publications in < 5 years; delivering 5 talks and presenting 5+ posters at leading conferences in my field at both local and international levels.
email: javierh@phas.ubc.ca
twitter_username: lorem_ipsum
github_username:  
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-86798464-2"

exclude: ['package.json', 'src' , 'node_modules']
