title: Oscar Javier Hernandez
description: My Personal Blog
author: Oscar Javier Hernandez
logo: /static/img/avatar.png
github: https://github.com/OscarJHernandez
about: Data Science | Machine Learning | AI

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: OscarJHernandez
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
