title: Oscar Javier Hernandez
description: The home page for Oscar Javier Hernandez
author: Oscar Javier Hernandez
logo: /static/img/avatar.png
github: https://github.com/OscarJHernandez
about: Data Science | AI | Machine Learning
email: javierh@phas.ubc.ca
linkedin: in/oscar-javier-hernandez/
baseurl: ""
url: ""

allowsearch: true

disqus_shortname: OscarJHernandez
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
