# Site settings
title: OscarJavierHernandez
markdown: kramdown
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oscar Javier Hernandez
user_description: Problem solving physics PhD student leveraging my quantitative and numerical skills to transition into data science. My research employs a range of statistical and numerical methodologies to produce state-of-the art calculations essential for precision experiments. Feel free to explore my website, I am open to feedback.
email: javierh@phas.ubc.ca
twitter_username: lorem_ipsum
github_username:  
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-86798464-2"

exclude: ['package.json', 'src' , 'node_modules']
